### ISSUE TITLE
メッセージ関連APIとの連携エラー

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#105]
コミュニティにメッセージ板がない状態で、コミュニティを切り替えるとエラーになる
![D9BAAB85-596D-4A2D-90B8-5440E4606665](https://user-images.githubusercontent.com/109019/57002779-d6221800-6bfc-11e9-9376-a48b7e2cedf5.png)

**Comment by inafact** [comment]
完全に切り分けできていませんが、メッセージ関連のいくつかの挙動がAPI側との兼ね合いありそうなのでタイトル変更しました。

いくつかクイストさん側に要確認な内容メモしておきます。

- [ ] コミュニティ内で自分がトピックを作成→削除した際、そのトピックのダイレクトメッセージのやりとりがあった場合、以降該当コミュニティのスレッド一覧を取得できなくなる

```
16:10:14.935 [qtp1179081741-240] INFO  commonsos.Server - [121.1.133.45][takanobu2][node04yc9a][XNKA1qvluw@LNzmwuiPwhQAAAEA] GET /message-threads?communityId=2
16:10:14.946 [qtp1179081741-240] ERROR commonsos.Server - [121.1.133.45][takanobu2][node04yc9a][XNKA1qvluw@LNzmwuiPwhQAAAEA] Bad request
commonsos.exception.AdNotFoundException: ad not found
        at java.util.Optional.orElseThrow(Optional.java:290)
        at commonsos.repository.AdRepository.findStrict(AdRepository.java:84)
        at commonsos.service.AdService.ad(AdService.java:85)
        at commonsos.service.AdService.view(AdService.java:81)
        at commonsos.service.MessageService.view(MessageService.java:182)
        at commonsos.service.MessageService.lambda$searchThreads$15(MessageService.java:216)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at commonsos.service.MessageService.searchThreads(MessageService.java:219)
        at commonsos.controller.message.MessageThreadListController.handleAfterLogin(MessageThreadListController.java:40)
        at commonsos.controller.message.MessageThreadListController.handleAfterLogin(MessageThreadListController.java:22)
        at commonsos.controller.AfterLoginController.handle(AfterLoginController.java:24)
        at commonsos.repository.EntityManagerService.runInTransaction(EntityManagerService.java:76)
        at commonsos.interceptor.TransactionInterceptor.proceedMethod(TransactionInterceptor.java:89)
        at commonsos.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:54)
        at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:564)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) 
        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
        at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
        at java.lang.Thread.run(Thread.java:748)
```

リクエスト自体は問題なさそう？に見えるが、Bad Request 扱いになってしまう？
