### ISSUE TITLE
メッセージ相手選択画面から先に飛ばない

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#90]
HorristicKaga アカウントからhorristicを選択までして、メッセージを送ろうとすると、選択画面から先に飛ばない。
共にパスワードは12345678

**Comment by hiroyuki** [comment]
そのあと、「データの取得に失敗しました」というアラートが出るのでおそらくAPIの呼び出し周りではないかと思います。

**Comment by hiroyuki** [comment]
```
19:14:12.699 [qtp918936714-105] ERROR commonsos.Server - [118.241.21.179][HorristicKaga][node051ae1][XLrw9PIi@hisGzwmjOQOjAAAAAc] Bad request
commonsos.exception.BadRequestException: User isn't a member of the community. [communityId=1]
        at commonsos.service.MessageService.createMessageThreadWithUser(MessageService.java:76)
        at commonsos.service.MessageService.lambda$threadWithUser$1(MessageService.java:70)
        at java.util.Optional.orElseGet(Optional.java:267)
        at commonsos.service.MessageService.threadWithUser(MessageService.java:70)
        at commonsos.controller.message.MessageThreadWithUserController.handleAfterLogin(MessageThreadWithUserController.java:35)
        at commonsos.controller.AfterLoginController.handle(AfterLoginController.java:24)
        at commonsos.repository.EntityManagerService.runInTransaction(EntityManagerService.java:76)
        at commonsos.interceptor.TransactionInterceptor.proceedMethod(TransactionInterceptor.java:89)
        at commonsos.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:51)
        at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:564)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
        at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
        at java.lang.Thread.run(Thread.java:748)
```
このエラーがでてるので、おそらくcommunityIDのパラメータが間違っているようです！

**Comment by inafact** [comment]
@hiroyuki 

手元の端末で試してみたんですが、送れてしいました..

サーバーのエラーログ的には、確かにcommunity Idの設定がうまくいっていないようです。
おそらくこちら、 #85 のissueと原因が同じで、ログイン時のカレントのコミュニティ設定が正しくできていないのではという感じです（何度かアプリのインストール・アンインストールを繰り返した際に似たような状況に遭遇しました）。

#85 とマージして調査してみます。

merged #85
